add_definitions(-DNOMINMAX -DWIN32_LEAN_AND_MEAN -D_XKEYCHECK_H -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_WARNINGS -D_USE_MATH_DEFINES -DDISABLE_WEAK_CALLBACKS -D_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS -D_WIN32_WINNT=0x0600 -DUNICODE -D_UNICODE /permissive- /experimental:preprocessor)
set(MSVC_TOOLSET_VERSION 144)
